Add apps api.
kabobcompany/kc-sdk-app-ruby pull request #1
Opened 2022-09-12 10:51 UTC by tswenja

2022-09-12 13:00 UTC, emn178 requested changes

2022-09-12 13:00 UTC, emn178 commented on lib/kc-sdk-app/api.rb
> +      self.access_token = KcSdkApp.configuration.access_token
讓access_token做為初始化參數帶進來

2022-09-12 13:00 UTC, emn178 commented on README.md
> +#### Apps
文件加上 Api.new 的用法

2022-09-13 03:49 UTC, tswenja commented on lib/kc-sdk-app/api.rb
> +      self.access_token = KcSdkApp.configuration.access_token
已更新

2022-09-13 03:50 UTC, tswenja commented on README.md
> +#### Apps
已更新

2022-09-13 03:52 UTC, emn178 approved these changes

2022-09-13 03:52 UTC, merged